name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: "${{ matrix.label }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Ruby 3.1 & Active Support 7"
            ruby-version: "3.1"
            active-support-version: "7"
          - name: "Ruby 3.0 & Active Support 7"
            ruby-version: "3.0"
            active-support-version: "7"
          - name: "Ruby 2.7 & Active Support 7"
            ruby-version: "2.7"
            active-support-version: "7"
          - name: "Ruby 3.0 & Active Support 6"
            ruby-version: "3.0"
            active-support-version: "6"
          - name: "Ruby 2.7 & Active Support 6"
            ruby-version: "2.7"
            active-support-version: "6"
          - name: "Ruby 2.6 & Active Support 6"
            ruby-version: "2.6"
            active-support-version: "6"
          - name: "Ruby 2.7 & Active Support 5"
            ruby-version: "2.7"
            active-support-version: "5"
          - name: "Ruby 2.6 & Active Support 5"
            ruby-version: "2.6"
            active-support-version: "5"
    env:
      BUNDLE_GEMFILE: gemfiles/activesupport${{ matrix.activesupport-version }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake test
